//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationContext : DbContext
    {
        public ApplicationContext()
            : base("name=ApplicationContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category_Details> Category_Details { get; set; }
        public DbSet<Country_Details> Country_Details { get; set; }
        public DbSet<Note_Details> Note_Details { get; set; }
        public DbSet<NotesAttachment> NotesAttachments { get; set; }
        public DbSet<Purchase_Details> Purchase_Details { get; set; }
        public DbSet<Review_Details> Review_Details { get; set; }
        public DbSet<Spam_Notes> Spam_Notes { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<System_Config> System_Config { get; set; }
        public DbSet<Type_Details> Type_Details { get; set; }
        public DbSet<User_Details> User_Details { get; set; }
        public DbSet<User_Roles> User_Roles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
