//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_Details
    {
        public Note_Details()
        {
            this.NotesAttachments = new HashSet<NotesAttachment>();
            this.Purchase_Details = new HashSet<Purchase_Details>();
            this.Review_Details = new HashSet<Review_Details>();
            this.Spam_Notes = new HashSet<Spam_Notes>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Category_Id { get; set; }
        public string Image { get; set; }
        public int Type_Id { get; set; }
        public Nullable<decimal> Pages { get; set; }
        public string Description { get; set; }
        public string University { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public string Course { get; set; }
        public string Course_Code { get; set; }
        public string Professor { get; set; }
        public decimal Price { get; set; }
        public string Note_Preview { get; set; }
        public int Status { get; set; }
        public System.DateTime Added_Date { get; set; }
        public Nullable<int> Review_By { get; set; }
        public Nullable<System.DateTime> Published_Date { get; set; }
        public int User_Id { get; set; }
        public Nullable<System.DateTime> Edited_Date { get; set; }
        public bool IsActive { get; set; }
        public string AdminReview { get; set; }
    
        public virtual Category_Details Category_Details { get; set; }
        public virtual Country_Details Country_Details { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Type_Details Type_Details { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<NotesAttachment> NotesAttachments { get; set; }
        public virtual ICollection<Purchase_Details> Purchase_Details { get; set; }
        public virtual ICollection<Review_Details> Review_Details { get; set; }
        public virtual ICollection<Spam_Notes> Spam_Notes { get; set; }
    }
}
