//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review_Details
    {
        public int Review_Id { get; set; }
        public int User_Id { get; set; }
        public int Note_Id { get; set; }
        public int Purchase_Id { get; set; }
        public string Review_msg { get; set; }
        public System.DateTime Review_Date { get; set; }
        public int Rating { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Note_Details Note_Details { get; set; }
        public virtual Purchase_Details Purchase_Details { get; set; }
        public virtual User User { get; set; }
    }
}
