//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spam_Notes
    {
        public int Id { get; set; }
        public int NoteId { get; set; }
        public int UserId { get; set; }
        public int Purchase_Id { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Reported_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Note_Details Note_Details { get; set; }
        public virtual Purchase_Details Purchase_Details { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
