//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Note_Details = new HashSet<Note_Details>();
            this.User_Details = new HashSet<User_Details>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public string DataValue { get; set; }
        public string RefCategory { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Note_Details> Note_Details { get; set; }
        public virtual ICollection<User_Details> User_Details { get; set; }
    }
}
