//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Secondary_Email { get; set; }
        public string Phone_No_Country_Code { get; set; }
        public decimal Phone_No { get; set; }
        public string Profile_Img { get; set; }
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public int Country_Id { get; set; }
        public string University { get; set; }
        public string College { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
