//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Category_Details = new HashSet<Category_Details>();
            this.Category_Details1 = new HashSet<Category_Details>();
            this.Country_Details = new HashSet<Country_Details>();
            this.Country_Details1 = new HashSet<Country_Details>();
            this.Note_Details = new HashSet<Note_Details>();
            this.NotesAttachments = new HashSet<NotesAttachment>();
            this.Purchase_Details = new HashSet<Purchase_Details>();
            this.Purchase_Details1 = new HashSet<Purchase_Details>();
            this.Purchase_Details2 = new HashSet<Purchase_Details>();
            this.Review_Details = new HashSet<Review_Details>();
            this.Spam_Notes = new HashSet<Spam_Notes>();
            this.Spam_Notes1 = new HashSet<Spam_Notes>();
            this.Type_Details = new HashSet<Type_Details>();
            this.Type_Details1 = new HashSet<Type_Details>();
            this.User_Details = new HashSet<User_Details>();
        }
    
        public int UserId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.DateTime Create_Date { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Category_Details> Category_Details { get; set; }
        public virtual ICollection<Category_Details> Category_Details1 { get; set; }
        public virtual ICollection<Country_Details> Country_Details { get; set; }
        public virtual ICollection<Country_Details> Country_Details1 { get; set; }
        public virtual ICollection<Note_Details> Note_Details { get; set; }
        public virtual ICollection<NotesAttachment> NotesAttachments { get; set; }
        public virtual ICollection<Purchase_Details> Purchase_Details { get; set; }
        public virtual ICollection<Purchase_Details> Purchase_Details1 { get; set; }
        public virtual ICollection<Purchase_Details> Purchase_Details2 { get; set; }
        public virtual ICollection<Review_Details> Review_Details { get; set; }
        public virtual ICollection<Spam_Notes> Spam_Notes { get; set; }
        public virtual ICollection<Spam_Notes> Spam_Notes1 { get; set; }
        public virtual ICollection<Type_Details> Type_Details { get; set; }
        public virtual ICollection<Type_Details> Type_Details1 { get; set; }
        public virtual ICollection<User_Details> User_Details { get; set; }
        public virtual User_Roles User_Roles { get; set; }
    }
}
