//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roles
    {
        public User_Roles()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Role_Id { get; set; }
        public string Role { get; set; }
        public System.DateTime Create_Date { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
